# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - set PATH=%PATH%;C:\tools\ChocolateyPackageUpdater
  - ps: Invoke-WebRequest -OutFile noel.exe -Uri https://github.com/pine613/noel/releases/download/auto-release-master-e664839/noel.exe
  - choco install chocolateypackageupdater

test_script:
  - noel --install
 
# what combinations to test


init:
  - git config --global core.autocrlf false
  
build: off
deploy: off
