# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - set GOPATH=%cd%
  - set PATH=%PATH%;%cd%\bin
	- choco install chocolateypackageupdater
  - go get github.com/pine613/noel

test_script:
  - noel --install
 
# what combinations to test


init:
  - git config --global core.autocrlf false
  
build: off
deploy: off
