# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - set PATH=%PATH%;C:\tools\ChocolateyPackageUpdater
  - choco install 7zip.commandline
  - ps: Invoke-WebRequest -OutFile noel.zip -Uri https://github.com/pine613/noel/releases/download/v1.0.0beta1/noel_v1.0.0beta1.zip
  - 7za e noel.zip
  - choco install chocolateypackageupdater

test_script:
  - noel --install
 
# what combinations to test


init:
  - git config --global core.autocrlf false
  
build: off
deploy: off
